[package]
name = "swayspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"
structopt = "0.3.25"
swayipc = "2.7.2"

